export const BLOG_MAIN_SUBSCRIBERS_ID = 'BLOG-MAIN';
export const BLOG_MAKER_SUBSCRIBERS_ID = 'BLOG-MAKER';
export const BLOG_PAGES_SUBSCRIBERS_ID = 'BLOG-PAGES';
export const BLOG_POSTS_SUBSCRIBERS_ID = 'BLOG-POSTS';
export const BLOG_COMMENTS_SUBSCRIBERS_ID = 'BLOG-COMMENTS';
