import { Routes } from '@angular/router';

import {
  ACTIVATE_ROUTE,
  PASSWORD_RESET_FINISH_ROUTE,
  PASSWORD_RESET_INIT_ROUTE,
  SIGN_IN_ROUTE,
  SIGN_UP_ROUTE,
  SIGN_UP_RESULT_ROUTE
} from './';

export const INTERNAL_ROUTES: Routes = [
  {
    path: '',
    children: [ACTIVATE_ROUTE, PASSWORD_RESET_FINISH_ROUTE, PASSWORD_RESET_INIT_ROUTE, SIGN_IN_ROUTE, SIGN_UP_ROUTE, SIGN_UP_RESULT_ROUTE]
  }
];
